/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PersistentPersistentAffiliateAccountDetails = IDL.Record({
  'bankAccountNumber' : IDL.Opt(IDL.Text),
  'validTillDate' : IDL.Opt(IDL.Text),
  'ifscCode' : IDL.Opt(IDL.Text),
  'accountHolderName' : IDL.Opt(IDL.Text),
  'bankName' : IDL.Opt(IDL.Text),
  'accountType' : IDL.Opt(IDL.Text),
  'accountCreationDate' : IDL.Opt(IDL.Text),
  'upiId' : IDL.Opt(IDL.Text),
  'branchName' : IDL.Opt(IDL.Text),
  'verificationStatus' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProfitCalculation = IDL.Record({
  'adminCut' : IDL.Nat,
  'expectedEarnings' : IDL.Nat,
  'referralBonus' : IDL.Nat,
  'netProfit' : IDL.Nat,
});
export const Time = IDL.Int;
export const Deal = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'shareCount' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'commissionPercent' : IDL.Nat,
  'trendingTag' : IDL.Text,
  'targetRegion' : IDL.Text,
  'affiliateLink' : IDL.Text,
  'price' : IDL.Nat,
});
export const AdminCommissionSummary = IDL.Record({
  'adminTotal' : IDL.Nat,
  'lastUpdated' : Time,
});
export const AdminStats = IDL.Record({
  'totalPendingWithdrawals' : IDL.Nat,
  'totalCommissionPaid' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalDeals' : IDL.Nat,
  'totalApprovedWithdrawals' : IDL.Nat,
});
export const AffiliateAccountStats = IDL.Record({
  'validAccounts' : IDL.Nat,
  'unverifiedAccounts' : IDL.Nat,
  'inactiveAccounts' : IDL.Nat,
  'expiredAccounts' : IDL.Nat,
  'verifiedAccounts' : IDL.Nat,
  'activeAccounts' : IDL.Nat,
  'totalAccounts' : IDL.Nat,
});
export const PersistentAdminAffiliateSettings = IDL.Record({
  'id' : IDL.Nat,
  'username' : IDL.Opt(IDL.Text),
  'websiteUrl' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Opt(IDL.Principal),
  'lastUpdated' : IDL.Opt(Time),
  'lastUpdatedBy' : IDL.Opt(IDL.Principal),
  'apiKey' : IDL.Opt(IDL.Text),
  'notes' : IDL.Text,
  'affiliateId' : IDL.Text,
  'contactEmail' : IDL.Opt(IDL.Text),
  'supportPhone' : IDL.Opt(IDL.Text),
  'platformName' : IDL.Text,
});
export const TransactionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const TransactionType = IDL.Variant({
  'adjustment' : IDL.Null,
  'referral' : IDL.Null,
  'commission' : IDL.Null,
  'share' : IDL.Null,
  'withdrawal' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'status' : TransactionStatus,
  'transactionType' : TransactionType,
  'userId' : IDL.Principal,
  'note' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});
export const User = IDL.Record({
  'referralCode' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'pendingEarnings' : IDL.Nat,
  'email' : IDL.Text,
  'shareCount' : IDL.Nat,
  'referredBy' : IDL.Opt(IDL.Text),
  'totalEarnings' : IDL.Nat,
  'isAdmin' : IDL.Bool,
  'mobile' : IDL.Text,
  'withdrawnAmount' : IDL.Nat,
  'walletBalance' : IDL.Nat,
});
export const LeaderboardEntry = IDL.Record({
  'referralCode' : IDL.Text,
  'name' : IDL.Text,
  'totalEarnings' : IDL.Nat,
});
export const MessageRole = IDL.Variant({
  'user' : IDL.Null,
  'assistant' : IDL.Null,
});
export const Message = IDL.Record({
  'role' : MessageRole,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const TransactionStatusSummary = IDL.Record({
  'pendingCount' : IDL.Nat,
  'approvedCount' : IDL.Nat,
  'lastUpdated' : Time,
  'totalTransactions' : IDL.Nat,
  'rejectedCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDeal' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'addMessage' : IDL.Func([IDL.Text], [], []),
  'addOrUpdateAffiliateAccount' : IDL.Func(
      [PersistentPersistentAffiliateAccountDetails],
      [],
      [],
    ),
  'adjustWalletBalance' : IDL.Func([IDL.Principal, IDL.Int], [], []),
  'approveWithdrawal' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateProfit' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [ProfitCalculation],
      ['query'],
    ),
  'clearMessages' : IDL.Func([], [], []),
  'creditCommission' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Text], [], []),
  'deleteDeal' : IDL.Func([IDL.Nat], [], []),
  'getActiveDeals' : IDL.Func([], [IDL.Vec(Deal)], ['query']),
  'getAdminCommissionSummary' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(AdminCommissionSummary)],
      ['query'],
    ),
  'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
  'getAffiliateAccount' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PersistentPersistentAffiliateAccountDetails)],
      [],
    ),
  'getAffiliateAccountStats' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(AffiliateAccountStats)],
      ['query'],
    ),
  'getAllAdminAffiliateSettings' : IDL.Func(
      [],
      [IDL.Vec(PersistentAdminAffiliateSettings)],
      ['query'],
    ),
  'getAllAffiliateAccounts' : IDL.Func(
      [],
      [IDL.Vec(PersistentPersistentAffiliateAccountDetails)],
      ['query'],
    ),
  'getAllDeals' : IDL.Func([], [IDL.Vec(Deal)], ['query']),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getTransactionStatusSummary' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(TransactionStatusSummary)],
      ['query'],
    ),
  'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUser' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'register' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'rejectWithdrawal' : IDL.Func([IDL.Nat], [], []),
  'requestWithdrawal' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'saveAdminAffiliateSettings' : IDL.Func(
      [PersistentAdminAffiliateSettings],
      [IDL.Nat],
      [],
    ),
  'setAdmin' : IDL.Func([IDL.Principal], [], []),
  'trackShare' : IDL.Func([IDL.Nat], [], []),
  'updateAdminCommissionSummary' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateAffiliateAccountStats' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'updateDeal' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateTransactionStatusSummary' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'updateUser' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PersistentPersistentAffiliateAccountDetails = IDL.Record({
    'bankAccountNumber' : IDL.Opt(IDL.Text),
    'validTillDate' : IDL.Opt(IDL.Text),
    'ifscCode' : IDL.Opt(IDL.Text),
    'accountHolderName' : IDL.Opt(IDL.Text),
    'bankName' : IDL.Opt(IDL.Text),
    'accountType' : IDL.Opt(IDL.Text),
    'accountCreationDate' : IDL.Opt(IDL.Text),
    'upiId' : IDL.Opt(IDL.Text),
    'branchName' : IDL.Opt(IDL.Text),
    'verificationStatus' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProfitCalculation = IDL.Record({
    'adminCut' : IDL.Nat,
    'expectedEarnings' : IDL.Nat,
    'referralBonus' : IDL.Nat,
    'netProfit' : IDL.Nat,
  });
  const Time = IDL.Int;
  const Deal = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'shareCount' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'commissionPercent' : IDL.Nat,
    'trendingTag' : IDL.Text,
    'targetRegion' : IDL.Text,
    'affiliateLink' : IDL.Text,
    'price' : IDL.Nat,
  });
  const AdminCommissionSummary = IDL.Record({
    'adminTotal' : IDL.Nat,
    'lastUpdated' : Time,
  });
  const AdminStats = IDL.Record({
    'totalPendingWithdrawals' : IDL.Nat,
    'totalCommissionPaid' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalDeals' : IDL.Nat,
    'totalApprovedWithdrawals' : IDL.Nat,
  });
  const AffiliateAccountStats = IDL.Record({
    'validAccounts' : IDL.Nat,
    'unverifiedAccounts' : IDL.Nat,
    'inactiveAccounts' : IDL.Nat,
    'expiredAccounts' : IDL.Nat,
    'verifiedAccounts' : IDL.Nat,
    'activeAccounts' : IDL.Nat,
    'totalAccounts' : IDL.Nat,
  });
  const PersistentAdminAffiliateSettings = IDL.Record({
    'id' : IDL.Nat,
    'username' : IDL.Opt(IDL.Text),
    'websiteUrl' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Opt(IDL.Principal),
    'lastUpdated' : IDL.Opt(Time),
    'lastUpdatedBy' : IDL.Opt(IDL.Principal),
    'apiKey' : IDL.Opt(IDL.Text),
    'notes' : IDL.Text,
    'affiliateId' : IDL.Text,
    'contactEmail' : IDL.Opt(IDL.Text),
    'supportPhone' : IDL.Opt(IDL.Text),
    'platformName' : IDL.Text,
  });
  const TransactionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const TransactionType = IDL.Variant({
    'adjustment' : IDL.Null,
    'referral' : IDL.Null,
    'commission' : IDL.Null,
    'share' : IDL.Null,
    'withdrawal' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'status' : TransactionStatus,
    'transactionType' : TransactionType,
    'userId' : IDL.Principal,
    'note' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  const User = IDL.Record({
    'referralCode' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'pendingEarnings' : IDL.Nat,
    'email' : IDL.Text,
    'shareCount' : IDL.Nat,
    'referredBy' : IDL.Opt(IDL.Text),
    'totalEarnings' : IDL.Nat,
    'isAdmin' : IDL.Bool,
    'mobile' : IDL.Text,
    'withdrawnAmount' : IDL.Nat,
    'walletBalance' : IDL.Nat,
  });
  const LeaderboardEntry = IDL.Record({
    'referralCode' : IDL.Text,
    'name' : IDL.Text,
    'totalEarnings' : IDL.Nat,
  });
  const MessageRole = IDL.Variant({
    'user' : IDL.Null,
    'assistant' : IDL.Null,
  });
  const Message = IDL.Record({
    'role' : MessageRole,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const TransactionStatusSummary = IDL.Record({
    'pendingCount' : IDL.Nat,
    'approvedCount' : IDL.Nat,
    'lastUpdated' : Time,
    'totalTransactions' : IDL.Nat,
    'rejectedCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDeal' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'addMessage' : IDL.Func([IDL.Text], [], []),
    'addOrUpdateAffiliateAccount' : IDL.Func(
        [PersistentPersistentAffiliateAccountDetails],
        [],
        [],
      ),
    'adjustWalletBalance' : IDL.Func([IDL.Principal, IDL.Int], [], []),
    'approveWithdrawal' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateProfit' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [ProfitCalculation],
        ['query'],
      ),
    'clearMessages' : IDL.Func([], [], []),
    'creditCommission' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Text], [], []),
    'deleteDeal' : IDL.Func([IDL.Nat], [], []),
    'getActiveDeals' : IDL.Func([], [IDL.Vec(Deal)], ['query']),
    'getAdminCommissionSummary' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(AdminCommissionSummary)],
        ['query'],
      ),
    'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
    'getAffiliateAccount' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PersistentPersistentAffiliateAccountDetails)],
        [],
      ),
    'getAffiliateAccountStats' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(AffiliateAccountStats)],
        ['query'],
      ),
    'getAllAdminAffiliateSettings' : IDL.Func(
        [],
        [IDL.Vec(PersistentAdminAffiliateSettings)],
        ['query'],
      ),
    'getAllAffiliateAccounts' : IDL.Func(
        [],
        [IDL.Vec(PersistentPersistentAffiliateAccountDetails)],
        ['query'],
      ),
    'getAllDeals' : IDL.Func([], [IDL.Vec(Deal)], ['query']),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getTransactionStatusSummary' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(TransactionStatusSummary)],
        ['query'],
      ),
    'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUser' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'register' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'rejectWithdrawal' : IDL.Func([IDL.Nat], [], []),
    'requestWithdrawal' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'saveAdminAffiliateSettings' : IDL.Func(
        [PersistentAdminAffiliateSettings],
        [IDL.Nat],
        [],
      ),
    'setAdmin' : IDL.Func([IDL.Principal], [], []),
    'trackShare' : IDL.Func([IDL.Nat], [], []),
    'updateAdminCommissionSummary' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateAffiliateAccountStats' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
        ],
        [],
        [],
      ),
    'updateDeal' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateTransactionStatusSummary' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'updateUser' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };