/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminCommissionSummary {
  'adminTotal' : bigint,
  'lastUpdated' : Time,
}
export interface AdminStats {
  'totalPendingWithdrawals' : bigint,
  'totalCommissionPaid' : bigint,
  'totalUsers' : bigint,
  'totalDeals' : bigint,
  'totalApprovedWithdrawals' : bigint,
}
export interface AffiliateAccountStats {
  'validAccounts' : bigint,
  'unverifiedAccounts' : bigint,
  'inactiveAccounts' : bigint,
  'expiredAccounts' : bigint,
  'verifiedAccounts' : bigint,
  'activeAccounts' : bigint,
  'totalAccounts' : bigint,
}
export interface Deal {
  'id' : bigint,
  'title' : string,
  'createdAt' : Time,
  'description' : string,
  'isActive' : boolean,
  'shareCount' : bigint,
  'imageUrl' : string,
  'commissionPercent' : bigint,
  'trendingTag' : string,
  'targetRegion' : string,
  'affiliateLink' : string,
  'price' : bigint,
}
export type KycDocType = { 'pan' : null } |
  { 'aadhaar' : null };
export interface KycRecord {
  'status' : KycStatus,
  'docNumber' : string,
  'userId' : Principal,
  'rejectionReason' : [] | [string],
  'submittedAt' : Time,
  'reviewedAt' : [] | [Time],
  'docType' : KycDocType,
}
export type KycStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface LeaderboardEntry {
  'referralCode' : string,
  'name' : string,
  'totalEarnings' : bigint,
}
export interface Message {
  'role' : MessageRole,
  'message' : string,
  'timestamp' : Time,
}
export type MessageRole = { 'user' : null } |
  { 'assistant' : null };
export interface PersistentAdminAffiliateSettings {
  'id' : bigint,
  'username' : [] | [string],
  'websiteUrl' : string,
  'createdAt' : Time,
  'createdBy' : [] | [Principal],
  'lastUpdated' : [] | [Time],
  'lastUpdatedBy' : [] | [Principal],
  'apiKey' : [] | [string],
  'notes' : string,
  'affiliateId' : string,
  'contactEmail' : [] | [string],
  'supportPhone' : [] | [string],
  'platformName' : string,
}
export interface PersistentPersistentAffiliateAccountDetails {
  'bankAccountNumber' : [] | [string],
  'validTillDate' : [] | [string],
  'ifscCode' : [] | [string],
  'accountHolderName' : [] | [string],
  'bankName' : [] | [string],
  'accountType' : [] | [string],
  'accountCreationDate' : [] | [string],
  'upiId' : [] | [string],
  'branchName' : [] | [string],
  'verificationStatus' : [] | [string],
}
export interface PersistentPurchaseClaim {
  'id' : bigint,
  'status' : PurchaseClaimStatus,
  'trackingCode' : string,
  'userId' : Principal,
  'createdAt' : Time,
  'confirmedAt' : [] | [Time],
  'rejectionReason' : [] | [string],
  'purchaseAmount' : bigint,
  'dealId' : bigint,
  'userCommissionAmount' : bigint,
  'reviewedAt' : [] | [Time],
  'adminCommissionAmount' : bigint,
  'commissionAmount' : bigint,
}
export interface ProfitCalculation {
  'adminCut' : bigint,
  'expectedEarnings' : bigint,
  'referralBonus' : bigint,
  'netProfit' : bigint,
}
export type PurchaseClaimStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type Time = bigint;
export interface Transaction {
  'id' : bigint,
  'status' : TransactionStatus,
  'transactionType' : TransactionType,
  'userId' : Principal,
  'note' : string,
  'timestamp' : Time,
  'amount' : bigint,
}
export type TransactionStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface TransactionStatusSummary {
  'pendingCount' : bigint,
  'approvedCount' : bigint,
  'lastUpdated' : Time,
  'totalTransactions' : bigint,
  'rejectedCount' : bigint,
}
export type TransactionType = { 'adjustment' : null } |
  { 'referral' : null } |
  { 'commission' : null } |
  { 'share' : null } |
  { 'withdrawal' : null };
export interface User {
  'referralCode' : string,
  'name' : string,
  'createdAt' : Time,
  'pendingEarnings' : bigint,
  'email' : string,
  'shareCount' : bigint,
  'referredBy' : [] | [string],
  'totalEarnings' : bigint,
  'isAdmin' : boolean,
  'mobile' : string,
  'withdrawnAmount' : bigint,
  'walletBalance' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDeal' : ActorMethod<
    [string, string, bigint, string, bigint, string, string, string],
    bigint
  >,
  'addMessage' : ActorMethod<[string], undefined>,
  'addOrUpdateAffiliateAccount' : ActorMethod<
    [PersistentPersistentAffiliateAccountDetails],
    undefined
  >,
  'adjustWalletBalance' : ActorMethod<[Principal, bigint], undefined>,
  'approveKyc' : ActorMethod<[Principal], undefined>,
  'approvePurchaseClaim' : ActorMethod<[bigint], undefined>,
  'approveWithdrawal' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateProfit' : ActorMethod<[bigint, bigint], ProfitCalculation>,
  'clearMessages' : ActorMethod<[], undefined>,
  'confirmPurchase' : ActorMethod<[string, bigint], undefined>,
  'createTrackingLink' : ActorMethod<[bigint], string>,
  'creditCommission' : ActorMethod<[Principal, bigint, string], undefined>,
  'deleteDeal' : ActorMethod<[bigint], undefined>,
  'generateOtp' : ActorMethod<[string, string], string>,
  'getActiveDeals' : ActorMethod<[], Array<Deal>>,
  'getAdminCommissionSummary' : ActorMethod<
    [string],
    [] | [AdminCommissionSummary]
  >,
  'getAdminEarningsPool' : ActorMethod<[], bigint>,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getAffiliateAccount' : ActorMethod<
    [Principal],
    [] | [PersistentPersistentAffiliateAccountDetails]
  >,
  'getAffiliateAccountStats' : ActorMethod<
    [string],
    [] | [AffiliateAccountStats]
  >,
  'getAllAdminAffiliateSettings' : ActorMethod<
    [],
    Array<PersistentAdminAffiliateSettings>
  >,
  'getAllAffiliateAccounts' : ActorMethod<
    [],
    Array<PersistentPersistentAffiliateAccountDetails>
  >,
  'getAllDeals' : ActorMethod<[], Array<Deal>>,
  'getAllKyc' : ActorMethod<[], Array<KycRecord>>,
  'getAllPurchaseClaims' : ActorMethod<[], Array<PersistentPurchaseClaim>>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [User]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getMessages' : ActorMethod<[], Array<Message>>,
  'getMyKyc' : ActorMethod<[], [] | [KycRecord]>,
  'getMyPurchaseClaims' : ActorMethod<[], Array<PersistentPurchaseClaim>>,
  'getTransactionStatusSummary' : ActorMethod<
    [string],
    [] | [TransactionStatusSummary]
  >,
  'getTransactions' : ActorMethod<[], Array<Transaction>>,
  'getUser' : ActorMethod<[], [] | [User]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [User]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'register' : ActorMethod<[string, string, string, [] | [string]], undefined>,
  'rejectKyc' : ActorMethod<[Principal, string], undefined>,
  'rejectPurchaseClaim' : ActorMethod<[bigint, string], undefined>,
  'rejectWithdrawal' : ActorMethod<[bigint], undefined>,
  'requestWithdrawal' : ActorMethod<[bigint], bigint>,
  'saveAdminAffiliateSettings' : ActorMethod<
    [PersistentAdminAffiliateSettings],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[User], undefined>,
  'setAdmin' : ActorMethod<[Principal], undefined>,
  'submitKyc' : ActorMethod<[KycDocType, string], undefined>,
  'trackShare' : ActorMethod<[bigint], undefined>,
  'updateAdminCommissionSummary' : ActorMethod<[string, bigint], undefined>,
  'updateAffiliateAccountStats' : ActorMethod<
    [string, bigint, bigint, bigint, bigint, bigint, bigint, bigint],
    undefined
  >,
  'updateDeal' : ActorMethod<
    [bigint, string, string, bigint, string, bigint, string, string, string],
    undefined
  >,
  'updateTransactionStatusSummary' : ActorMethod<
    [string, bigint, bigint, bigint, bigint],
    undefined
  >,
  'updateUser' : ActorMethod<[string], undefined>,
  'verifyOtp' : ActorMethod<[string, string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];