/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PersistentPersistentAffiliateAccountDetails {
    bankAccountNumber?: string;
    validTillDate?: string;
    ifscCode?: string;
    accountHolderName?: string;
    bankName?: string;
    accountType?: string;
    accountCreationDate?: string;
    upiId?: string;
    branchName?: string;
    verificationStatus?: string;
}
export interface LeaderboardEntry {
    referralCode: string;
    name: string;
    totalEarnings: bigint;
}
export type Time = bigint;
export interface User {
    referralCode: string;
    name: string;
    createdAt: Time;
    pendingEarnings: bigint;
    email: string;
    shareCount: bigint;
    referredBy?: string;
    totalEarnings: bigint;
    isAdmin: boolean;
    mobile: string;
    withdrawnAmount: bigint;
    walletBalance: bigint;
}
export interface PersistentAdminAffiliateSettings {
    id: bigint;
    username?: string;
    websiteUrl: string;
    createdAt: Time;
    createdBy?: Principal;
    lastUpdated?: Time;
    lastUpdatedBy?: Principal;
    apiKey?: string;
    notes: string;
    affiliateId: string;
    contactEmail?: string;
    supportPhone?: string;
    platformName: string;
}
export interface AdminCommissionSummary {
    adminTotal: bigint;
    lastUpdated: Time;
}
export interface Transaction {
    id: bigint;
    status: TransactionStatus;
    transactionType: TransactionType;
    userId: Principal;
    note: string;
    timestamp: Time;
    amount: bigint;
}
export interface AdminStats {
    totalPendingWithdrawals: bigint;
    totalCommissionPaid: bigint;
    totalUsers: bigint;
    totalDeals: bigint;
    totalApprovedWithdrawals: bigint;
}
export interface KycRecord {
    status: KycStatus;
    docNumber: string;
    userId: Principal;
    rejectionReason?: string;
    submittedAt: Time;
    reviewedAt?: Time;
    docType: KycDocType;
}
export interface AffiliateAccountStats {
    validAccounts: bigint;
    unverifiedAccounts: bigint;
    inactiveAccounts: bigint;
    expiredAccounts: bigint;
    verifiedAccounts: bigint;
    activeAccounts: bigint;
    totalAccounts: bigint;
}
export interface Deal {
    id: bigint;
    title: string;
    createdAt: Time;
    description: string;
    isActive: boolean;
    shareCount: bigint;
    imageUrl: string;
    commissionPercent: bigint;
    trendingTag: string;
    targetRegion: string;
    affiliateLink: string;
    price: bigint;
}
export interface ProfitCalculation {
    adminCut: bigint;
    expectedEarnings: bigint;
    referralBonus: bigint;
    netProfit: bigint;
}
export interface Message {
    role: MessageRole;
    message: string;
    timestamp: Time;
}
export interface TransactionStatusSummary {
    pendingCount: bigint;
    approvedCount: bigint;
    lastUpdated: Time;
    totalTransactions: bigint;
    rejectedCount: bigint;
}
export enum KycDocType {
    pan = "pan",
    aadhaar = "aadhaar"
}
export enum MessageRole {
    user = "user",
    assistant = "assistant"
}
export enum TransactionStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum TransactionType {
    adjustment = "adjustment",
    referral = "referral",
    commission = "commission",
    share = "share",
    withdrawal = "withdrawal"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addDeal(title: string, imageUrl: string, price: bigint, affiliateLink: string, commissionPercent: bigint, trendingTag: string, targetRegion: string, description: string): Promise<bigint>;
    addMessage(message: string): Promise<void>;
    addOrUpdateAffiliateAccount(details: PersistentPersistentAffiliateAccountDetails): Promise<void>;
    adjustWalletBalance(userId: Principal, amount: bigint): Promise<void>;
    approveKyc(userId: Principal): Promise<void>;
    approveWithdrawal(transactionId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    calculateProfit(productPrice: bigint, commissionPercent: bigint): Promise<ProfitCalculation>;
    clearMessages(): Promise<void>;
    creditCommission(userId: Principal, amount: bigint, note: string): Promise<void>;
    deleteDeal(id: bigint): Promise<void>;
    generateOtp(email: string, mobile: string): Promise<string>;
    getActiveDeals(): Promise<Array<Deal>>;
    getAdminCommissionSummary(adminName: string): Promise<AdminCommissionSummary | null>;
    getAdminStats(): Promise<AdminStats>;
    getAffiliateAccount(accountId: Principal): Promise<PersistentPersistentAffiliateAccountDetails | null>;
    getAffiliateAccountStats(statsId: string): Promise<AffiliateAccountStats | null>;
    getAllAdminAffiliateSettings(): Promise<Array<PersistentAdminAffiliateSettings>>;
    getAllAffiliateAccounts(): Promise<Array<PersistentPersistentAffiliateAccountDetails>>;
    getAllDeals(): Promise<Array<Deal>>;
    getAllKyc(): Promise<Array<KycRecord>>;
    getAllTransactions(): Promise<Array<Transaction>>;
    getAllUsers(): Promise<Array<User>>;
    getCallerUserRole(): Promise<UserRole>;
    getLeaderboard(): Promise<Array<LeaderboardEntry>>;
    getMessages(): Promise<Array<Message>>;
    getMyKyc(): Promise<KycRecord | null>;
    getTransactionStatusSummary(summaryId: string): Promise<TransactionStatusSummary | null>;
    getTransactions(): Promise<Array<Transaction>>;
    getUser(): Promise<User | null>;
    isCallerAdmin(): Promise<boolean>;
    register(name: string, email: string, mobile: string, referralCode: string | null): Promise<void>;
    rejectKyc(userId: Principal, reason: string): Promise<void>;
    rejectWithdrawal(transactionId: bigint): Promise<void>;
    requestWithdrawal(amount: bigint): Promise<bigint>;
    saveAdminAffiliateSettings(settings: PersistentAdminAffiliateSettings): Promise<bigint>;
    setAdmin(user: Principal): Promise<void>;
    submitKyc(docType: KycDocType, docNumber: string): Promise<void>;
    trackShare(dealId: bigint): Promise<void>;
    updateAdminCommissionSummary(adminName: string, adminTotal: bigint): Promise<void>;
    updateAffiliateAccountStats(statsId: string, totalAccounts: bigint, verifiedAccounts: bigint, unverifiedAccounts: bigint, activeAccounts: bigint, inactiveAccounts: bigint, validAccounts: bigint, expiredAccounts: bigint): Promise<void>;
    updateDeal(id: bigint, title: string, imageUrl: string, price: bigint, affiliateLink: string, commissionPercent: bigint, trendingTag: string, targetRegion: string, description: string): Promise<void>;
    updateTransactionStatusSummary(summaryId: string, totalTransactions: bigint, pendingCount: bigint, approvedCount: bigint, rejectedCount: bigint): Promise<void>;
    updateUser(name: string): Promise<void>;
    verifyOtp(email: string, mobile: string, code: string): Promise<boolean>;
}
import type { AdminCommissionSummary as _AdminCommissionSummary, AffiliateAccountStats as _AffiliateAccountStats, KycDocType as _KycDocType, KycRecord as _KycRecord, KycStatus as _KycStatus, Message as _Message, MessageRole as _MessageRole, PersistentAdminAffiliateSettings as _PersistentAdminAffiliateSettings, PersistentPersistentAffiliateAccountDetails as _PersistentPersistentAffiliateAccountDetails, Time as _Time, Transaction as _Transaction, TransactionStatus as _TransactionStatus, TransactionStatusSummary as _TransactionStatusSummary, TransactionType as _TransactionType, User as _User, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addDeal(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: bigint, arg5: string, arg6: string, arg7: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addDeal(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDeal(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async addMessage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMessage(arg0);
            return result;
        }
    }
    async addOrUpdateAffiliateAccount(arg0: PersistentPersistentAffiliateAccountDetails): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateAffiliateAccount(to_candid_PersistentPersistentAffiliateAccountDetails_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateAffiliateAccount(to_candid_PersistentPersistentAffiliateAccountDetails_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async adjustWalletBalance(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adjustWalletBalance(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adjustWalletBalance(arg0, arg1);
            return result;
        }
    }
    async approveKyc(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveKyc(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveKyc(arg0);
            return result;
        }
    }
    async approveWithdrawal(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveWithdrawal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveWithdrawal(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async calculateProfit(arg0: bigint, arg1: bigint): Promise<ProfitCalculation> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateProfit(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateProfit(arg0, arg1);
            return result;
        }
    }
    async clearMessages(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearMessages();
            return result;
        }
    }
    async creditCommission(arg0: Principal, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.creditCommission(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.creditCommission(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteDeal(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDeal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDeal(arg0);
            return result;
        }
    }
    async generateOtp(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateOtp(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateOtp(arg0, arg1);
            return result;
        }
    }
    async getActiveDeals(): Promise<Array<Deal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveDeals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveDeals();
            return result;
        }
    }
    async getAdminCommissionSummary(arg0: string): Promise<AdminCommissionSummary | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminCommissionSummary(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminCommissionSummary(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminStats(): Promise<AdminStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminStats();
            return result;
        }
    }
    async getAffiliateAccount(arg0: Principal): Promise<PersistentPersistentAffiliateAccountDetails | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAffiliateAccount(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAffiliateAccount(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAffiliateAccountStats(arg0: string): Promise<AffiliateAccountStats | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAffiliateAccountStats(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAffiliateAccountStats(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAdminAffiliateSettings(): Promise<Array<PersistentAdminAffiliateSettings>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAdminAffiliateSettings();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAdminAffiliateSettings();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAffiliateAccounts(): Promise<Array<PersistentPersistentAffiliateAccountDetails>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAffiliateAccounts();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAffiliateAccounts();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDeals(): Promise<Array<Deal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDeals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDeals();
            return result;
        }
    }
    async getAllKyc(): Promise<Array<KycRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllKyc();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllKyc();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTransactions();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTransactions();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderboard(): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return result;
        }
    }
    async getMessages(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyKyc(): Promise<KycRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyKyc();
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyKyc();
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionStatusSummary(arg0: string): Promise<TransactionStatusSummary | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionStatusSummary(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionStatusSummary(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactions();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactions();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUser(): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser();
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser();
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async register(arg0: string, arg1: string, arg2: string, arg3: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0, arg1, arg2, to_candid_opt_n43(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0, arg1, arg2, to_candid_opt_n43(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async rejectKyc(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectKyc(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectKyc(arg0, arg1);
            return result;
        }
    }
    async rejectWithdrawal(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectWithdrawal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectWithdrawal(arg0);
            return result;
        }
    }
    async requestWithdrawal(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.requestWithdrawal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestWithdrawal(arg0);
            return result;
        }
    }
    async saveAdminAffiliateSettings(arg0: PersistentAdminAffiliateSettings): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveAdminAffiliateSettings(to_candid_PersistentAdminAffiliateSettings_n44(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveAdminAffiliateSettings(to_candid_PersistentAdminAffiliateSettings_n44(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setAdmin(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdmin(arg0);
            return result;
        }
    }
    async submitKyc(arg0: KycDocType, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitKyc(to_candid_KycDocType_n46(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitKyc(to_candid_KycDocType_n46(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async trackShare(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.trackShare(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.trackShare(arg0);
            return result;
        }
    }
    async updateAdminCommissionSummary(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAdminCommissionSummary(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAdminCommissionSummary(arg0, arg1);
            return result;
        }
    }
    async updateAffiliateAccountStats(arg0: string, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint, arg7: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAffiliateAccountStats(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAffiliateAccountStats(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async updateDeal(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: bigint, arg6: string, arg7: string, arg8: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDeal(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDeal(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async updateTransactionStatusSummary(arg0: string, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTransactionStatusSummary(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTransactionStatusSummary(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateUser(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUser(arg0);
            return result;
        }
    }
    async verifyOtp(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyOtp(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyOtp(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_KycDocType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KycDocType): KycDocType {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_KycRecord_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KycRecord): KycRecord {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_KycStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KycStatus): KycStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_MessageRole_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageRole): MessageRole {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Message_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Message {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_PersistentAdminAffiliateSettings_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PersistentAdminAffiliateSettings): PersistentAdminAffiliateSettings {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_PersistentPersistentAffiliateAccountDetails_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PersistentPersistentAffiliateAccountDetails): PersistentPersistentAffiliateAccountDetails {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionStatus): TransactionStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_User_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AffiliateAccountStats]): AffiliateAccountStats | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_KycRecord]): KycRecord | null {
    return value.length === 0 ? null : from_candid_KycRecord_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TransactionStatusSummary]): TransactionStatusSummary | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : from_candid_User_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AdminCommissionSummary]): AdminCommissionSummary | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PersistentPersistentAffiliateAccountDetails]): PersistentPersistentAffiliateAccountDetails | null {
    return value.length === 0 ? null : from_candid_PersistentPersistentAffiliateAccountDetails_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    username: [] | [string];
    websiteUrl: string;
    createdAt: _Time;
    createdBy: [] | [Principal];
    lastUpdated: [] | [_Time];
    lastUpdatedBy: [] | [Principal];
    apiKey: [] | [string];
    notes: string;
    affiliateId: string;
    contactEmail: [] | [string];
    supportPhone: [] | [string];
    platformName: string;
}): {
    id: bigint;
    username?: string;
    websiteUrl: string;
    createdAt: Time;
    createdBy?: Principal;
    lastUpdated?: Time;
    lastUpdatedBy?: Principal;
    apiKey?: string;
    notes: string;
    affiliateId: string;
    contactEmail?: string;
    supportPhone?: string;
    platformName: string;
} {
    return {
        id: value.id,
        username: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.username)),
        websiteUrl: value.websiteUrl,
        createdAt: value.createdAt,
        createdBy: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.createdBy)),
        lastUpdated: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.lastUpdated)),
        lastUpdatedBy: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.lastUpdatedBy)),
        apiKey: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.apiKey)),
        notes: value.notes,
        affiliateId: value.affiliateId,
        contactEmail: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.contactEmail)),
        supportPhone: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.supportPhone)),
        platformName: value.platformName
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _KycStatus;
    docNumber: string;
    userId: Principal;
    rejectionReason: [] | [string];
    submittedAt: _Time;
    reviewedAt: [] | [_Time];
    docType: _KycDocType;
}): {
    status: KycStatus;
    docNumber: string;
    userId: Principal;
    rejectionReason?: string;
    submittedAt: Time;
    reviewedAt?: Time;
    docType: KycDocType;
} {
    return {
        status: from_candid_KycStatus_n20(_uploadFile, _downloadFile, value.status),
        docNumber: value.docNumber,
        userId: value.userId,
        rejectionReason: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.rejectionReason)),
        submittedAt: value.submittedAt,
        reviewedAt: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.reviewedAt)),
        docType: from_candid_KycDocType_n22(_uploadFile, _downloadFile, value.docType)
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TransactionStatus;
    transactionType: _TransactionType;
    userId: Principal;
    note: string;
    timestamp: _Time;
    amount: bigint;
}): {
    id: bigint;
    status: TransactionStatus;
    transactionType: TransactionType;
    userId: Principal;
    note: string;
    timestamp: Time;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_TransactionStatus_n27(_uploadFile, _downloadFile, value.status),
        transactionType: from_candid_TransactionType_n28(_uploadFile, _downloadFile, value.transactionType),
        userId: value.userId,
        note: value.note,
        timestamp: value.timestamp,
        amount: value.amount
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    referralCode: string;
    name: string;
    createdAt: _Time;
    pendingEarnings: bigint;
    email: string;
    shareCount: bigint;
    referredBy: [] | [string];
    totalEarnings: bigint;
    isAdmin: boolean;
    mobile: string;
    withdrawnAmount: bigint;
    walletBalance: bigint;
}): {
    referralCode: string;
    name: string;
    createdAt: Time;
    pendingEarnings: bigint;
    email: string;
    shareCount: bigint;
    referredBy?: string;
    totalEarnings: bigint;
    isAdmin: boolean;
    mobile: string;
    withdrawnAmount: bigint;
    walletBalance: bigint;
} {
    return {
        referralCode: value.referralCode,
        name: value.name,
        createdAt: value.createdAt,
        pendingEarnings: value.pendingEarnings,
        email: value.email,
        shareCount: value.shareCount,
        referredBy: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.referredBy)),
        totalEarnings: value.totalEarnings,
        isAdmin: value.isAdmin,
        mobile: value.mobile,
        withdrawnAmount: value.withdrawnAmount,
        walletBalance: value.walletBalance
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    role: _MessageRole;
    message: string;
    timestamp: _Time;
}): {
    role: MessageRole;
    message: string;
    timestamp: Time;
} {
    return {
        role: from_candid_MessageRole_n38(_uploadFile, _downloadFile, value.role),
        message: value.message,
        timestamp: value.timestamp
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bankAccountNumber: [] | [string];
    validTillDate: [] | [string];
    ifscCode: [] | [string];
    accountHolderName: [] | [string];
    bankName: [] | [string];
    accountType: [] | [string];
    accountCreationDate: [] | [string];
    upiId: [] | [string];
    branchName: [] | [string];
    verificationStatus: [] | [string];
}): {
    bankAccountNumber?: string;
    validTillDate?: string;
    ifscCode?: string;
    accountHolderName?: string;
    bankName?: string;
    accountType?: string;
    accountCreationDate?: string;
    upiId?: string;
    branchName?: string;
    verificationStatus?: string;
} {
    return {
        bankAccountNumber: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.bankAccountNumber)),
        validTillDate: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.validTillDate)),
        ifscCode: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.ifscCode)),
        accountHolderName: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.accountHolderName)),
        bankName: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.bankName)),
        accountType: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.accountType)),
        accountCreationDate: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.accountCreationDate)),
        upiId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.upiId)),
        branchName: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.branchName)),
        verificationStatus: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.verificationStatus))
    };
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): TransactionStatus {
    return "pending" in value ? TransactionStatus.pending : "approved" in value ? TransactionStatus.approved : "rejected" in value ? TransactionStatus.rejected : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pan: null;
} | {
    aadhaar: null;
}): KycDocType {
    return "pan" in value ? KycDocType.pan : "aadhaar" in value ? KycDocType.aadhaar : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    adjustment: null;
} | {
    referral: null;
} | {
    commission: null;
} | {
    share: null;
} | {
    withdrawal: null;
}): TransactionType {
    return "adjustment" in value ? TransactionType.adjustment : "referral" in value ? TransactionType.referral : "commission" in value ? TransactionType.commission : "share" in value ? TransactionType.share : "withdrawal" in value ? TransactionType.withdrawal : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user: null;
} | {
    assistant: null;
}): MessageRole {
    return "user" in value ? MessageRole.user : "assistant" in value ? MessageRole.assistant : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PersistentAdminAffiliateSettings>): Array<PersistentAdminAffiliateSettings> {
    return value.map((x)=>from_candid_PersistentAdminAffiliateSettings_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PersistentPersistentAffiliateAccountDetails>): Array<PersistentPersistentAffiliateAccountDetails> {
    return value.map((x)=>from_candid_PersistentPersistentAffiliateAccountDetails_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_KycRecord>): Array<KycRecord> {
    return value.map((x)=>from_candid_KycRecord_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Array<Message> {
    return value.map((x)=>from_candid_Message_n36(_uploadFile, _downloadFile, x));
}
function to_candid_KycDocType_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KycDocType): _KycDocType {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function to_candid_PersistentAdminAffiliateSettings_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PersistentAdminAffiliateSettings): _PersistentAdminAffiliateSettings {
    return to_candid_record_n45(_uploadFile, _downloadFile, value);
}
function to_candid_PersistentPersistentAffiliateAccountDetails_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PersistentPersistentAffiliateAccountDetails): _PersistentPersistentAffiliateAccountDetails {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bankAccountNumber?: string;
    validTillDate?: string;
    ifscCode?: string;
    accountHolderName?: string;
    bankName?: string;
    accountType?: string;
    accountCreationDate?: string;
    upiId?: string;
    branchName?: string;
    verificationStatus?: string;
}): {
    bankAccountNumber: [] | [string];
    validTillDate: [] | [string];
    ifscCode: [] | [string];
    accountHolderName: [] | [string];
    bankName: [] | [string];
    accountType: [] | [string];
    accountCreationDate: [] | [string];
    upiId: [] | [string];
    branchName: [] | [string];
    verificationStatus: [] | [string];
} {
    return {
        bankAccountNumber: value.bankAccountNumber ? candid_some(value.bankAccountNumber) : candid_none(),
        validTillDate: value.validTillDate ? candid_some(value.validTillDate) : candid_none(),
        ifscCode: value.ifscCode ? candid_some(value.ifscCode) : candid_none(),
        accountHolderName: value.accountHolderName ? candid_some(value.accountHolderName) : candid_none(),
        bankName: value.bankName ? candid_some(value.bankName) : candid_none(),
        accountType: value.accountType ? candid_some(value.accountType) : candid_none(),
        accountCreationDate: value.accountCreationDate ? candid_some(value.accountCreationDate) : candid_none(),
        upiId: value.upiId ? candid_some(value.upiId) : candid_none(),
        branchName: value.branchName ? candid_some(value.branchName) : candid_none(),
        verificationStatus: value.verificationStatus ? candid_some(value.verificationStatus) : candid_none()
    };
}
function to_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    username?: string;
    websiteUrl: string;
    createdAt: Time;
    createdBy?: Principal;
    lastUpdated?: Time;
    lastUpdatedBy?: Principal;
    apiKey?: string;
    notes: string;
    affiliateId: string;
    contactEmail?: string;
    supportPhone?: string;
    platformName: string;
}): {
    id: bigint;
    username: [] | [string];
    websiteUrl: string;
    createdAt: _Time;
    createdBy: [] | [Principal];
    lastUpdated: [] | [_Time];
    lastUpdatedBy: [] | [Principal];
    apiKey: [] | [string];
    notes: string;
    affiliateId: string;
    contactEmail: [] | [string];
    supportPhone: [] | [string];
    platformName: string;
} {
    return {
        id: value.id,
        username: value.username ? candid_some(value.username) : candid_none(),
        websiteUrl: value.websiteUrl,
        createdAt: value.createdAt,
        createdBy: value.createdBy ? candid_some(value.createdBy) : candid_none(),
        lastUpdated: value.lastUpdated ? candid_some(value.lastUpdated) : candid_none(),
        lastUpdatedBy: value.lastUpdatedBy ? candid_some(value.lastUpdatedBy) : candid_none(),
        apiKey: value.apiKey ? candid_some(value.apiKey) : candid_none(),
        notes: value.notes,
        affiliateId: value.affiliateId,
        contactEmail: value.contactEmail ? candid_some(value.contactEmail) : candid_none(),
        supportPhone: value.supportPhone ? candid_some(value.supportPhone) : candid_none(),
        platformName: value.platformName
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KycDocType): {
    pan: null;
} | {
    aadhaar: null;
} {
    return value == KycDocType.pan ? {
        pan: null
    } : value == KycDocType.aadhaar ? {
        aadhaar: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
